### ISSUE TITLE
HelloWorld

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#1]
Scrivere un programma per la stampa della stringa
"Hello, World!" utilizzando due chiamate a printf()

**Comment by LuigiVessella** [comment]
Ok, in hello.c ho scritto il codice con due richiami a printf()

**Comment by FabioZTessitore** [comment]
immagino che tu lo abbia compilato, vero?

**Comment by LuigiVessella** [comment]
Sisi

**Comment by LuigiVessella** [comment]
Anche eseguito

**Comment by FabioZTessitore** [comment]
nel programma ci sono errori, come può essere?

**Comment by LuigiVessella** [comment]
Ok ora l'ho compilato e va...avevo compilato il vostro, poi modificato hello.c e non compilato di nuovo ahah

**Comment by LuigiVessella** [comment]
Però l'ho modificato da qua che mi da errore nel push, ora rifaccio il clone..
