### ISSUE TITLE
maggiore tra tre

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#10]
![es2_19](https://cloud.githubusercontent.com/assets/3002194/20811789/481e5ff8-b80f-11e6-86ae-bf76d2c28ccd.jpg)

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
non va bene. devi trovare un altro algoritmo
puoi usare solo 2 if

**Comment by LuigiVessella** [comment]
Ah ok

Il 03 dic 2016 20:42, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Un if dentro a un if lo posso usare ahah?

**Comment by FabioZTessitore** [comment]
no

**Comment by LuigiVessella** [comment]
Prof datemi qualche altro consiglio per favore

**Comment by LuigiVessella** [comment]
Ho capito che devo fa l'ipotesi..Riguardo a cosa?

**Comment by FabioZTessitore** [comment]
la parte del massimo l'hai copiata dal sig ruzzon
la parte del minimo l'hai fatta tu, però è sbagliata

**Comment by LuigiVessella** [comment]
Il sig ruzzon mi ha solo aiutato, che non avevo capito nemmeno quanti if dovevo fare

**Comment by LuigiVessella** [comment]
L'ho aggiustato, testato e funziona
