### ISSUE TITLE
cifre

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#13]
![es2_30](https://cloud.githubusercontent.com/assets/3002194/21204923/f5f3d30c-c259-11e6-912c-ad21de10d63b.jpg)

**Comment by LuigiVessella** [comment]
mhh prof qualche consiglio? Ho numero tipo 45675 divido per 10000 e ottiengo 4 dato che la variabile è di tipo int. Poi come avanzo?

**Comment by FabioZTessitore** [comment]
puoi usare solo il numero 10, ti consiglio di partire da destra

**Comment by LuigiVessella** [comment]
Prof, innanzitutto tanti auguri e buone fatte feste.
In queste vacanze non mi ci sono proprio messo al pc e quindi lo carico ora...Il programma funziona in parte però noterete che le stampa al contrario, come posso risolvere?

**Comment by FabioZTessitore** [comment]
buone fatte feste anche a te

usa 5 variabili per le cifre così poi le stampi nell'ordine che preferisci

**Comment by LuigiVessella** [comment]
Ah va benissimo, ora le metto..

Il 08 gen 2017 13:16, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
fatto, caricato.

**Comment by LuigiVessella** [comment]
Prof visto?

Il 08 gen 2017 1:34 PM, "Luigi Vessella" <vessellaluigi12@gmail.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
ti ho mandato una mail

**Comment by LuigiVessella** [comment]
Sisi ora ho visto...si era buggato gmail

Il 09 gen 2017 16:58, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:
