### ISSUE TITLE
Figure

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#2]
![es2_21](https://cloud.githubusercontent.com/assets/3002194/20538563/0c910d6a-b0f2-11e6-8f24-70118db32b96.png)

**Comment by LuigiVessella** [comment]
Fatto! Compilato, eseguito e caricato..

**Comment by FabioZTessitore** [comment]
tu asserisci che se mando in esecuzione il tuo programma esce la figura come quella richiesta?

**Comment by LuigiVessella** [comment]
Si ma non tutte e 4 sulla stessa linea... 2 e 2

Il 25/nov/2016 20:51, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
e come devo fare per farti capire che devi fare le cose come vengono richieste?

**Comment by LuigiVessella** [comment]
Mi dovete picchiare ahah..
Quindi ora devo rifare vero?😢

Il 25/nov/2016 20:53, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
no ma è l'ultima volta. d'ora in avanti devi essere preciso
