### ISSUE TITLE
Stampa Iniziali

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#3]
![es2_25](https://cloud.githubusercontent.com/assets/3002194/20538605/3a2b2b2a-b0f2-11e6-9468-90f20a774533.png)

**Comment by FabioZTessitore** [comment]
il fatto che il programma sia semplice non implica che non debba essere scritto bene
1) aggiusta il codice (indentazioni)
2) cosa restituisce main?

**Comment by LuigiVessella** [comment]
Fatto(?)

**Comment by FabioZTessitore** [comment]
ma lo vedi cosa mi hai mandato?

**Comment by LuigiVessella** [comment]
Prof ma questi sono bug ahah..Vi giuro che non ho scritto quelle cose io ahah

**Comment by FabioZTessitore** [comment]
ma dopo aver fatto delle modifiche bisogna ricompilare per vedere se ci sono bug
