### ISSUE TITLE
Stampa Scacchiera

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#4]
![es2_27](https://cloud.githubusercontent.com/assets/3002194/20538619/48cd74da-b0f2-11e6-838b-4ad83d44ca6c.jpg)

**Comment by LuigiVessella** [comment]
Prof io in classe mi so scordato di caricarla qui la scacchiera, mo sta sul pc a scuola...mo che carico le figure potete andare avanti lo stesso??

**Comment by LuigiVessella** [comment]
L'avevo fatta bene, sia con 8 printf sia con un printf e gli \n....
