### ISSUE TITLE
variabili int

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#5]
guarda il file variabili_int.c e dimmi se tutto chiaro

**Comment by LuigiVessella** [comment]
Chiaro!

**Comment by FabioZTessitore** [comment]
guarda input_int.c

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
Dai un'occhiata al file `/usr/include/limits.h`
e crea un programma che stampa il valore
delle variabili `INT_MIN` e `INT_MAX`

**Comment by LuigiVessella** [comment]
Ok

Il 27 nov 2016 14:21, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
Posso usare #define per dichiarare INT_MIN e INT_MAX, come in limits.h?

**Comment by LuigiVessella** [comment]
Ok, l'ho fatto in due modi(in poche parole basta togliere i commenti per avere il secondo), ora lo carico

**Comment by FabioZTessitore** [comment]
ok, lo sai che `\n` puoi metterli nella stringa ed evitare quelle chiamate?
poi togli tutti quegli spazi inutili da riga 13 in poi

**Comment by LuigiVessella** [comment]
Si si lo so, distrazione...ora correggo

Il 27 nov 2016 15:33, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
per quale ragione dovresti definirli tu se stanno in limits.h?

**Comment by LuigiVessella** [comment]
Si per ciò ho messo i commenti...avevo questo dubbio... credevo che non la
dovevo includere la libreria..

Il 27 nov 2016 15:34, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by LuigiVessella** [comment]
fatto
