### ISSUE TITLE
cerchio

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#7]
![es2_20](https://cloud.githubusercontent.com/assets/3002194/20649437/9bf18bb6-b4c0-11e6-9d59-4ef923157144.jpg)

**Comment by LuigiVessella** [comment]
Quindi le devo dichiarare float giusto?

**Comment by FabioZTessitore** [comment]
l'esercizio richiede che i calcoli vengano fatti nella printf

**Comment by LuigiVessella** [comment]
si dico il raggio deve essere float?

**Comment by FabioZTessitore** [comment]
no, in C sai leggere solo int

**Comment by LuigiVessella** [comment]
Fatto
