### ISSUE TITLE
caratteri

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/helloworld_c#8]
![es2_29](https://cloud.githubusercontent.com/assets/3002194/20649615/c58630dc-b4c3-11e6-8110-f6195b934c74.jpg)

**Comment by LuigiVessella** [comment]
Fatto!

**Comment by FabioZTessitore** [comment]
mi spieghi perché continui a mettere tutti quegli a capo dopo l'ultima istruzione?
